// Builds docs/js/levels.js: 100 levels (10 worlds x 10 levels).
// Run from the repo root:  node tools/make-levels.mjs
//
// Each level gets a target "air time" that grows from 1.3 s to 12 s. The tower
// height is solved so a jump really lasts that long, then the flip goal is set
// to a fair share of the flips you could do in that time.
import { writeFileSync } from 'node:fs';
import { WORLDS } from '../docs/js/data.js';
import { levelPhysics, simulate, SPIN_TIME } from '../docs/js/physics.js';

const round = (v, digits = 0) => Math.round(v * 10 ** digits) / 10 ** digits;

// seconds in the air for level n (1..100)
const targetTime = (n) => 1.3 + 10.7 * ((n - 1) / 99) ** 0.9;

// After level 20 you fall faster and faster, so towers can grow to about 2 km
// without jumps taking forever.
const speedScale = (n) => (n <= 20 ? 1 : 1 + 7.5 * ((n - 20) / 80) ** 1.5);

function niceHeight(h) {
  if (h < 100) return Math.round(h);
  if (h < 1000) return Math.round(h / 5) * 5;
  return Math.round(h / 10) * 10;
}

function solveHeight(phys, seconds) {
  let lo = 1, hi = 8000;
  for (let i = 0; i < 40; i++) {
    const mid = (lo + hi) / 2;
    if (simulate(phys, mid).t < seconds) lo = mid; else hi = mid;
  }
  return (lo + hi) / 2;
}

const levels = [];
for (let n = 1; n <= 100; n++) {
  const w = Math.floor((n - 1) / 10);
  const k = (n - 1) % 10;
  const world = WORLDS[w];
  const level = { name: world.names[k], world: w, theme: world.themes[k % world.themes.length] };

  if (world.gravity) {
    Object.assign(level, { gravity: world.gravity, jump: world.jump, terminal: world.terminal });
  } else if (speedScale(n) > 1) {
    const s = speedScale(n);
    Object.assign(level, { gravity: round(14 * Math.sqrt(s), 1), terminal: round(22 * s, 1) });
  }

  const phys = levelPhysics(level);
  level.height = niceHeight(solveHeight(phys, targetTime(n)));
  const air = simulate(phys, level.height).t;

  // goals: button tricks on every third level, a perfect landing on every 10th
  level.tricks = n >= 8 && n % 3 === 2 ? 1 + Math.floor(n / 33) : 0;
  level.perfect = n % 10 === 0;
  const share = 0.55 + (0.25 * (n - 1)) / 99 - (level.perfect ? 0.1 : 0);
  level.flips = Math.max(1, Math.floor(((air - level.tricks * 0.7) / SPIN_TIME) * share));
  level.air = round(air, 1);
  levels.push(level);
}

const fields = (l) => {
  const parts = [
    `name: '${l.name.replace(/'/g, "\\'")}'`, `world: ${l.world}`, `theme: '${l.theme}'`,
    `height: ${l.height}`, `flips: ${l.flips}`, `tricks: ${l.tricks}`, `perfect: ${l.perfect}`,
  ];
  if (l.gravity) parts.push(`gravity: ${l.gravity}`);
  if (l.jump) parts.push(`jump: ${l.jump}`);
  if (l.terminal) parts.push(`terminal: ${l.terminal}`);
  return `  { ${parts.join(', ')} }, // ${l.air} s`;
};

const out = `// Generated by tools/make-levels.mjs. Don't edit by hand: change the generator
// or WORLDS in data.js, then run: node tools/make-levels.mjs
//
// height: tower height in meters. flips / tricks: goal for one landed jump.
// perfect: the landing must be a PERFECT one. The comment is the time in the air.
export const LEVELS = [
${levels.map(fields).join('\n')}
];
`;
writeFileSync(new URL('../docs/js/levels.js', import.meta.url), out);

for (const l of levels) {
  console.log(`${String(levels.indexOf(l) + 1).padStart(3)} ${l.name.padEnd(16)} ${String(l.height).padStart(5)} m  ${String(l.air).padStart(5)} s  flips ${String(l.flips).padStart(2)}  tricks ${l.tricks}${l.perfect ? '  PERFECT' : ''}${l.gravity ? `  g=${l.gravity} vt=${l.terminal}` : ''}`);
}
